### ISSUE TITLE
PhysicsClientHandle.set_time_stamp should be called set_time_step

### ISSUE THREAD

**Issue by jice-nospam** [not-fl3/bulletrs#9]
I can provide a PR but wanted to know if there was a particular reason. It confused me and I had to check the source code to understand it was actually the timeStep that was modified.

**Comment by not-fl3** [comment]
Yes, probably its a typo (no idea why it was named that way). Thanks! 

https://github.com/not-fl3/bulletrs/commit/d11b489a55b34c93088052ff51042bfe54bac4c0
